spring:
  datasource:
    url: jdbc:h2:~/testdb
    username: sa
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8000
  tomcat:
    connection-timeout: 30s
    threads:
      max: 100
      min-spare: 100
    accesslog:
      enabled: true
      suffix: log
      prefix: access_log
      rename-on-rotate: true
springdoc:
  packages-to-scan: com.zim.payment
  swagger-ui:
    path: /api-docs
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs.path: /api-docs/json
  api-docs.groups.enabled: true
  cache:
    disabled: true
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8